name: run migrations
on: push
jobs:
  # Service containers to run with `container-job`
  services:
    # Label used to access the service container
    postgres:
      # Docker Hub image
      image: postgres
      # Provide the password for postgres
      env:
        POSTGRES_HOST_AUTH_METHOD: true
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
  run-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2
      - name: Install Alembic
        run: uv install alembic
