name: run migrations
on: push
jobs:
  # Service containers to run with `container-job`
  services:
    # Label used to access the service container
    postgres:
      # Docker Hub image
      image: postgres
      # Provide the password for postgres
      env:
        POSTGRES_HOST_AUTH_METHOD: true
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
